name: CI.yml
on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Go env for lint
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.6

      - name: Install linter
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh \
            | sh -s -- -b $(go env GOPATH)/bin v2.5.0

      - name: Run linter
        run: golangci-lint run

  build:
    needs: lint
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            binary_name: amazing-automata
            artifact_name: linux-binary
          - os: windows-latest
            binary_name: amazing-automata
            artifact_name: windows-binary
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Go env for build
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.6

      - name: Install debs
        run: go get

      - name: Build the project
        run: go build

